# Generated by Django 5.2.1 on 2025-05-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='image',
            field=models.ImageField(null=True, upload_to='VoteChain-electionimage/'),
        ),
    ]
