# Generated by Django 5.2.1 on 2025-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0002_election_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(null=True, upload_to='VoteChain-candidateimage/'),
        ),
    ]
