# Generated by Django 5.2.1 on 2025-05-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0003_candidate_description_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='b_voteapp.election'),
        ),
    ]
