# Generated by Django 5.2.1 on 2025-05-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0004_candidate_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Sport Director', 'Sport Director')], max_length=100, null=True),
        ),
    ]
