# Generated by Django 5.2.1 on 2025-05-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0008_voter_user_date_of_birth_voter_user_gender_and_more'),
        ('b_voteapp', '0005_candidate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='a_userauthapp.college'),
        ),
    ]
