# Generated by Django 5.2.1 on 2025-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0006_election_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('Staff Election', 'Staff Election'), ('Student Election', 'Student Election')], max_length=50, null=True),
        ),
    ]
