# Generated by Django 5.2.1 on 2025-05-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0007_election_election_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='name',
            new_name='election_name',
        ),
    ]
