# Generated by Django 5.2.1 on 2025-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0008_rename_name_election_election_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
