# Generated by Django 5.2.1 on 2025-05-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0009_election_election_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(null=True, upload_to='VoteChain-candidateimage'),
        ),
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(null=True, upload_to='VoteChain-electionimage'),
        ),
    ]
