# Generated by Django 5.2.1 on 2025-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0010_alter_candidate_image_alter_election_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Sport Director', 'Sport Director')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Sport Director', 'Sport Director')], max_length=100, null=True),
        ),
    ]
