# Generated by Django 5.2.1 on 2025-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0011_candidate_staff_role_alter_candidate_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='staff_role',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
