# Generated by Django 5.2.1 on 2025-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_voteapp', '0015_alter_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(null=True, upload_to='E-Vote-Candidate Images'),
        ),
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(null=True, upload_to='E-Vote-Election Images'),
        ),
    ]
