# Generated by Django 5.2.1 on 2025-05-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='VoteChain-profileimages'),
        ),
    ]
