# Generated by Django 5.2.1 on 2025-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0004_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter_user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
