# Generated by Django 5.2.1 on 2025-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0007_college_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter_user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter_user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
