# Generated by Django 5.2.1 on 2025-05-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0009_remove_profile_gender_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
