# Generated by Django 5.2.1 on 2025-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_userauthapp', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='E-Vote-Profile Images'),
        ),
    ]
